version: '2.1'
services:
  mdns-advertise:
    restart: "always"
    build: .
    privileged: true
    network_mode: host
    labels:
      io.balena.features.dbus: '1'
    environment:
      DBUS_SYSTEM_BUS_ADDRESS: 'unix:path=/host/run/dbus/system_bus_socket'
      MDNS_TLD: 'testagain.local'
  # the hello container is just for testing purposes!
  hello:
    image: nginxdemos/nginx-hello:plain-text
    network_mode: host
